# Generated by Django 5.0.3 on 2024-04-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_husband_alter_women_tags_women_husband'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='husband',
        ),
        migrations.AddField(
            model_name='husband',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
